#pragma once
#define NOMINMAX
#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include <deque>
#include <thread>
#include <mutex>
#include <chrono>
#include <fmt/core.h>
#include <condition_variable>
#include <nlohmann/json.hpp>

#include <utility>
#include <glm/glm.hpp>
#include <glm/trigonometric.hpp>
#include <glm/gtc/constants.hpp>
#include <glm/gtc/bitfield.hpp>
#include <glm/gtc/round.hpp>
#include <glm/gtx/rotate_vector.hpp>
#include <glm/gtx/vector_angle.hpp>
#include <glm/gtx/quaternion.hpp>
#include <glm/exponential.hpp>
#include <glm/gtc/type_ptr.hpp>