set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)


if(PORT STREQUAL "assimp")
    list(APPEND VCPKGK_CMAKE_CONFIGURE_OPTIONS "-DASSIMP_DOUBLE_PRECISION=ON")
endif()